<script>
export default {
  companyName:'浙江南华资本管理有限公司',
  url:' https://www.easy-mock.com/mock/5cd125e7f13c0f52e6147e8e',
  nav:[{
    name:'用户权限管理',
    children:[{
      name:'本地用户维护',
      path:'/localUser/1'
    },{
      name:'OA用户维护',
      path:'/localUser/2'
    },{
      name:'角色维护',
      path:'/PFCG'
    },{
      name:'许可维护',
      path:'/PTM'
    },]
  },{
    name:'web客户端管理',
    children:[{
      name:'查看web端所有客户',
      path:'/allClient'
    },{
      name:'审核客户绑定',
      path:'/audit'
    },{
      name:'查看审核记录',
      path:'/seeAudit'
    },]
  },{
    name:'客户信息管理',
    path:'',
    children:[{
      name:'银行信息管理',
      path:'/bank'
    },{
      name:'部门信息管理',
      path:'/section'
    },{
      name:'辖区信息管理',
      path:'/area'
    },{
      name:'客户基本资料 ',
      path:'/clientDetails'
    },]
  },{
    name:'客户资金管理',
    path:'',
    children:[{
      name:'客户资金账户',
      path:'/capitalAccount '
    },]
  },{
    name:'报价配置管理',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'委托单管理',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'成交单管理',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'监控管理',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'结算管理',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'部门报表',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'营销统计',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'财务统计',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'营业部统计',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'报送监管机构',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'发送客户报表',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'日志管理',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'运维管理',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  },{
    name:'客户意见反馈',
    path:'',
    children:[{
      name:'',
      path:''
    },]
  }]
}
</script>
